version: '3'

tasks:
    bash:
        desc: Opens a bash shell in the container
        cmds:
            - docker compose exec php bash

    test:
        desc: Runs all tests
        cmds:
            - docker run --rm -v $(pwd):/app -v /var/run/docker.sock:/var/run/docker.sock airlock php vendor/bin/phpunit --display-all-issues
            #- docker compose exec php vendor/bin/phpunit --display-phpunit-notices --testdox

    coverage:text:
        desc: Show code coverage summary in terminal
        cmds:
            - docker run --rm -v $(pwd):/app -v /var/run/docker.sock:/var/run/docker.sock airlock php vendor/bin/phpunit --coverage-text

    phpstan:
        desc: Runs PHPStan
        cmds:
            - php vendor/bin/phpstan analyse --memory-limit=512M

    phpcs:
        desc: Runs PHPCS
        cmds:
            - php vendor/bin/phpcs --standard=phpcs.xml -v -p -s --colors

    phpcbf:
        desc: Runs PHPCBF
        cmds:
            - php vendor/bin/phpcbf --standard=phpcs.xml

    rector:
        desc: Runs Rector
        cmds:
            - php vendor/bin/rector process --dry-run







