version: '3'

tasks:
    test:
        desc: Runs all tests
        cmds:
            - docker run --rm -v $(pwd):/app -v /var/run/docker.sock:/var/run/docker.sock airlock php vendor/bin/phpunit

    phpstan:
        desc: Runs PHPStan
        cmds:
            - php vendor/bin/phpstan analyse --memory-limit=512M

    phpcs:
        desc: Runs PHPCS
        cmds:
            - php vendor/bin/phpcs --standard=phpcs.xml -v -p -s --colors

    phpcbf:
        desc: Runs PHPCBF
        cmds:
            - php vendor/bin/phpcbf --standard=ruleset.xml

    rector:
        desc: Runs Rector
        cmds:
            - php vendor/bin/rector process --dry-run



