version: '3'

tasks:
    test:
        desc: Runs all tests
        cmds:
            - docker compose exec php vendor/bin/phpunit --display-phpunit-notices --testdox

    phpstan:
        desc: Runs PHPStan
        cmds:
            - php vendor/bin/phpstan analyse --memory-limit=512M

    phpcs:
        desc: Runs PHPCS
        cmds:
            - php vendor/bin/phpcs --standard=phpcs.xml -v -p -s --colors

    phpcbf:
        desc: Runs PHPCBF
        cmds:
            - php vendor/bin/phpcbf --standard=phpcs.xml

    rector:
        desc: Runs Rector
        cmds:
            - php vendor/bin/rector process --dry-run







