version: '3'

rpc:
    listen: 'tcp://127.0.0.1:6001'

http:
    address: '0.0.0.0:8080'
    middleware:
        - gzip
        - static
        - http_metrics
    static:
        dir: public
        forbid:
            - .php
            - .htaccess
    pool:
        debug: true
        num_workers: 4
        supervisor:
            max_worker_memory: 100

server:
    command: 'php app.php'
    relay: pipes

kv:
    local:
        driver: memory
        config:
            interval: 60

metrics:
    address: 0.0.0.0:2112

    collect:
        airlock_entries_total:
            type: counter
            labels: [ "airlock", "result" ]

        airlock_leaves_total:
            type: counter
            labels: [ "airlock" ]

        airlock_releases_total:
            type: counter
            labels: [ "airlock" ]

        airlock_refreshes_total:
            type: counter
            labels: [ "airlock", "result" ]

        airlock_entry_duration_seconds:
            type: histogram
            labels: [ "airlock" ]
